//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: WaitSetData.cpp
//  Source: WaitSetData.idl
//  Generated: Sun Mar 29 12:04:23 2020
//  OpenSplice 6.9.181018OSS
//  
//******************************************************************

#include "WaitSetData.h"




